channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - pip
  - pyhdfe
  - statsmodels
  - scikit-learn
  - r-base=4.1
  - r-haven
  - r-data.table
  - r-MASS
  - r-lfe
  - r-glmmML
  - r-plm
  - r-fixest
  - r-here
  - r-tictoc
  - r-markdown
  - r-rmarkdown
  - r-tinytex
