---
author: "Notebook adapted from Laurent Berge and Grant McDermott"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    df_print: paged
---

This is an adaptation of Laurent Berge and Grant McDermott's walk through `fixest`. Full information available [here](https://cran.r-project.org/web/packages/fixest/vignettes/fixest_walkthrough.html).

# Fast Fixed-Effects Estimation: Short introduction

```{r setup}
#knitr::opts_knit$set(root.dir = '/Users/miguelportela/Documents/GitHub/HDFE/')

rm(list = ls())
gc()

library(here)
library(tictoc)
library(data.table)
library(haven)
library(plm)

# install.packages("fixest",repos = c(ropensci = 'https://fastverse.r-universe.dev',CRAN = 'https://cloud.r-project.org'))

library(fixest)
```


```{r A.0 Data}
data(trade)
nls <- read_dta("nlswork_regression.dta")
nls_nos <- read_dta("nlswork_regression_nosingleton.dta")
```

```{r A.1 My first model}
wages_feols <- feols(ln_wage ~ ttl_exp + union + not_smsa + nev_mar | idcode + year,nls)
print(wages_feols)
```

<!-- xtreg ln_wage ttl_exp union not_smsa nev_mar i.year, fe vce(cluster idcode) -->

```{r A.2 Wages FEOLS - NoSingleton}
wages_feols_nos <- feols(ln_wage ~ ttl_exp + union + not_smsa + nev_mar | idcode + year,nls,fixef.rm = "singleton")
summary(wages_feols_nos)
```



```{r A.3 Wages FEOLS - IID and NoSingleton}
wages_feols_nos_iid <- feols(ln_wage ~ ttl_exp + union + not_smsa + nev_mar | idcode + year,nls,fixef.rm = "singleton",vcov = "iid")
summary(wages_feols_nos_iid)
```


```{r A.4 Wages FEOLS - Cluster by idcode and NoSingleton}
wages_feols_nos_cluster <- feols(ln_wage ~ ttl_exp + union + not_smsa + nev_mar | idcode + year,nls,vcov = ~idcode,fixef.rm = "singleton")
summary(wages_feols_nos_cluster)
```

```{r A.5 Wages FEOLS - Cluster by idcode and year and NoSingleton}
wages_feols_nos_cluster <- feols(ln_wage ~ ttl_exp + union + not_smsa + nev_mar | idcode + year,nls,vcov = ~idcode + year,fixef.rm = "singleton")
summary(wages_feols_nos_cluster)
```
```{r A.6 Wages FEOLS - Cluster by idcode and year and NoSingleton}
wages_feols_nos_cluster <- feols(ln_wage ~ ttl_exp + union + not_smsa + nev_mar | idcode + year,nls,vcov = "twoway",fixef.rm = "singleton")
summary(wages_feols_nos_cluster)
```

```{r}
summary(wages_feols,vcov = "iid")
```


```{r}
summary(wages_feols_nos,vcov = "iid")
```

```{r A.8 Wages FEOLS - Cluster by idcode and NoSingleton and other var transform}
wages_feols_nos <- feols(ln_wage ~ log(ttl_exp) + union + not_smsa + nev_mar | idcode + year,nls,fixef.rm = "singleton")
summary(wages_feols_nos)
```


```{r A.9 Wages FEOLS - Cluster by idcode and NoSingleton and other features}
wages_feols <- feols(ln_wage ~ ttl_exp + union + not_smsa + nev_mar | idcode + year,nls,fixef.tol = 1e-6,fixef.iter = 200,fixef.rm = "singleton")
summary(wages_feols_nos)
```


```{r A.10 Viewing the results in R}
etable(wages_feols,wages_feols_nos,wages_feols_nos_iid,
         headers = c("Base","No Singleton","Org. IID"))

etable(wages_feols,wages_feols_nos,wages_feols_nos_iid,vcov = "twoway", headers = c("Base","No Singleton","Org. IID cluster"))
```


```{r A.1.5.2 Viewing the results in R}
gravity_subfe = list()
all_FEs = c("Year", "Destination", "Origin")
for(i in 0:3){
    gravity_subfe[[i+1]] = fepois(Euros ~ log(dist_km), trade, fixef = all_FEs[0:i])
}
```

```{r}
wages_subfe = list()
W_all_FEs = c("idcode","year")
for(i in 0:1){
    wages_subfe[[i+1]] = feols(ln_wage ~ ttl_exp + union + not_smsa + nev_mar,nls, fixef = W_all_FEs[0:i])
}
```


```{r A.1.5.3 Viewing the results in R}
etable(gravity_subfe, cluster = ~Origin+Destination)
```

```{r}
etable(wages_subfe, cluster = ~idcode+year)
```


```{r A.1.6 Multiple estimations}
res_multi = fepois(Euros ~ log(dist_km) | csw0(Year, Destination, Origin), trade)
```

```{r A.1.7 Exporting the results to Latex}
# with two-way clustered SEs
etable(res_multi, cluster = ~Origin+Destination, tex = TRUE,file = "_paper/Regressions.tex")
```


```{r A.1.7.1 An elaborate example}
# we set the dictionary once and for all
myDict = c("log(dist_km)" = "$\\ln (Distance)$", "(Intercept)" = "Constant")
# 1st export: we change the signif code and drop the intercept
etable(res_multi, signifCode = c("a" = 0.01, "b" = 0.05),
       drop = "Const", dict = myDict, file = "Estimation Tables.tex", 
       replace = TRUE, title = "First export -- normal Standard-errors")
# 2nd export: clustered S-E + distance as the first coefficient
etable(res_multi, cluster = ~Product, order = "Dist", 
       dict = myDict, file = "Estimation Tables.tex", 
       title = "Second export -- clustered standard-errors (on Product variable)")
```


```{r A.1.8 Extracting the fixed-effects coefficients}
fixedEffects = fixef(gravity_pois)
summary(fixedEffects)

fixedEffects$Year

```


```{r}
plot(fixedEffects)
```

```{r A.2 The vcov argument}
data(base_did)
est = feols(y ~ x1, base_did)
# Note that there is partial matching enabled (newey = newey_west)
summary(est, newey ~ id + period)
```


```{r, eval=FALSE}
summary(est, "newey_west")
```

```{r}
est_panel = feols(y ~ x1, base_did, panel.id = ~id + period)
summary(est_panel, "newey_west")
```

```{r}
setFixest_estimation(panel.id = ~id + period)
est_implicit = feols(y ~ x1, base_did)
summary(est_implicit, "newey_west")
```

```{r}
summary(est_implicit, "cluster")
```


```{r}
feols(y ~ x1 | period, base_did, "cluster")
```


```{r}
# Removing the panel
setFixest_estimation(reset = TRUE)
feols(y ~ x1 | period, base_did, "cluster")
```


```{r}
feols(y ~ x1 | period, base_did, ~id + period)
```


```{r}
data(quakes)
feols(depth ~ mag, quakes, "conley")
```


```{r A.2.2 Using dedicated functions}
feols(y ~ x1 | period, base_did, NW(2) ~ id + period)
```

```{r}
feols(depth ~ mag, quakes, conley(200, distance = "spherical"))
```

```{r}
feols(y ~ x1 | period, base_did, vcov_NW("id", "period", lag = 2))
```

```{r}
feols(depth ~ mag, quakes, vcov_conley(lat = "lat", lon = "long", 
                                       cutoff = 200, distance = "spherical"))
```

```{r A2.3 Small sample correction}
est = feols(y ~ x1 | id, base_did)
est_up = feols(y ~ x1 | id, base_did, ssc = ssc(fixef.K = "full"))
est_down = feols(y ~ x1 | id, base_did, ssc = ssc(adj = FALSE, cluster.adj = FALSE))
etable(est, est_up, est_down)
```


```{r}
etable(est, vcov = list(~id, ~id + ssc(fixef.K = "full"), 
                        ~id + ssc(adj = FALSE, cluster.adj = FALSE)))
```


```{r}
feols(y ~ x1 | id, base_did, iid ~ ssc(adj = FALSE))
```


```{r}
feols(y ~ x1 | id, base_did, hetero ~ ssc(adj = FALSE))
```

```{r A.2.4 Other types of VCOVs}
summary(est, vcov = sandwich::vcovHC, type = "HC1")
```


```{r}

```

```{r}
feols(y ~ x1 | id, base_did, vcov = function(x) sandwich::vcovHC(x, type = "HC1"))
```

```{r A.3 Instrumental variables}
base = iris
names(base) = c("y", "x1", "x_endo_1", "x_inst_1", "fe")
set.seed(2)
base$x_inst_2 = 0.2 * base$y + 0.2 * base$x_endo_1 + rnorm(150, sd = 0.5)
base$x_endo_2 = 0.2 * base$y - 0.2 * base$x_inst_1 + rnorm(150, sd = 0.5)

est_iv = feols(y ~ x1 | x_endo_1 + x_endo_2 ~ x_inst_1 + x_inst_2, base)
est_iv
```


```{r}
fitstat(est_iv, ~ ivf1 + ivwald1 + ivf2 + ivwald2, cluster = "fe")
```


```{r}
setFixest_print(fitstat = ~ . + ivwald2)
est_iv
```

```{r}
est_iv_fe = feols(y ~ x1 | fe | x_endo_1 + x_endo_2 ~ x_inst_1 + x_inst_2, base)
est_iv_fe
```


```{r}
summary(est_iv_fe, stage = 1)
```

```{r}
etable(summary(est_iv_fe, stage = 1:2), fitstat = ~ . + ivfall + ivwaldall.p)
```

```{r A.4.1 Interactions involving fixed-effects}
# Our base data for this section
base = iris
names(base) = c("y", paste0("x", 1:3), "fe1")
# Create another "fixed-effect"
base$fe2 = rep(letters[1:5], 30)
head(base)
```

```{r A.4.1.1 Combining several fixed-effects}
est_comb = feols(y ~ x1 | fe1^fe2, base)
est_comb
```

```{r}
fixef(est_comb)[[1]]
```



```{r A.4.1.2 Varying slopes (fe[x])}
head(base)
```

```{r}
est_vs = feols(y ~ x1 | fe1[x2], base)
est_vs
```


```{r}
summary(fixef(est_vs))
```

#### A.4.2 Interactions that don’t involve fixed-effects

```{r A.4.2.1 A compact syntax for factors and interactions: i()}
data(airquality)
res_i1 = feols(Ozone ~ Solar.R + i(Month), airquality)
res_i2 = feols(Ozone ~ Solar.R + i(Month, ref = 8), airquality)
res_i3 = feols(Ozone ~ Solar.R + i(Month, keep = 5:6), airquality)

etable(res_i1, res_i2, res_i3, dict = c("6" = "June", "Month::5" = "May"), 
       order = c("Int|May", "Mon"))
```

```{r A.4.2.2 Simple difference-in-differences (TWFE)}
# Sample data illustrating the DiD
data(base_did)
head(base_did)
```

```{r}
# Estimation of treatment × period effects
# We also add individual and period fixed-effects:
est_did = feols(y ~ x1 + i(period, treat, 5) | id + period, base_did)
est_did
```

```{r}
iplot(est_did)
```

```{r A.4.2.3 Staggered difference-in-differences (Sun and Abraham, 2020)}
data(base_stagg)

head(base_stagg)
```

```{r}
# "Naive" TWFE DiD (note that the time to treatment for the never treated is -1000)
# (by using ref = c(-1, -1000) we exclude the period just before the treatment and 
# the never treated)
res_twfe = feols(y ~ x1 + i(time_to_treatment, ref = c(-1, -1000)) | id + year, base_stagg)

# To implement the Sun and Abraham (2020) method,
# we use the sunab(cohort, period) function
res_sa20 = feols(y ~ x1 + sunab(year_treated, year) | id + year, base_stagg)
```


```{r}
# Plot the two TWFE results
iplot(list(res_twfe, res_sa20), sep = 0.5)

# Add the true results
att_true = tapply(base_stagg$treatment_effect_true, base_stagg$time_to_treatment, mean)[-1]
points(-9:8, att_true, pch = 15, col = 4)

legend("topleft", col = c(1, 4, 2), pch = c(20, 15, 17), 
       legend = c("TWFE", "Truth", "Sun & Abraham (2020)"))
```



```{r}
# The full ATT
summary(res_sa20, agg = "att")

```


```{r}
# Full disaggregation (you could have used summary instead of etable)
head(etable(res_sa20, agg = FALSE), 20)
```

#### A.5.1 Formula: macros and dot square brackets

```{r A.5.1.1 Formula macros}
base = iris
names(base) = c("y", "x1", "x2", "x3", "species")
# Defining the macro variables
setFixest_fml(..ctrl = ~poly(x2, 2) + poly(x3, 2))
# Accessing them
xpd(y ~ x1 + ..ctrl)
#> y ~ x1 + poly(x2, 2) + poly(x3, 2)

# Definition at run time
vars = c("x2", "x2^2", "x3")
for(i in 1:3){
  print(xpd(y ~ x1 + ..ctrl, ..ctrl = vars[1:i]))
}
```


```{r}
feols(y ~ x1 + ..ctrl, base)
```


```{r}
data(longley)
xpd(Armed.Forces ~ Population + regex("GNP|ployed"), data = longley)
```



```{r}
feols(Armed.Forces ~ Population + regex("GNP|ployed"), longley)
```


```{r A.5.1.2 The dot square bracket operator}
base = setNames(iris, c("y", "x1", "x2", "x3", "species"))
i = 2:3
z = "i(species)"
feols(y ~ x.[i] + .[z], base)
```


```{r}
i = 1:3
xpd(y ~ .["x.[i]_sq"])
```

```{r}
etable(feols(y ~ csw(x.[, 1:3]), base))
```

```{r}
vars = c("x1", "x2", "x3") # Equiv. to: dsb("x.[1:3]")
etable(feols(.[vars] ~ i(species), base))
```


```{r A.5.2.1 Lagging variables in an estimation}
est1 = feols(y ~ l(x1, 0:1), base_did, panel.id = ~id+period)
est2 = feols(f(y) ~ l(x1, -1:1), base_did, panel.id = ~id+period)
est3 = feols(l(y) ~ l(x1, 0:3), base_did, panel.id = ~id+period)
etable(est1, est2, est3, order = "f", drop = "Int")
```

```{r A.5.2.2 Setting up a panel data set}
# setting up the panel
pdat = panel(base_did, ~id + period)
# Now the panel.id argument is not required
est1 = feols(y ~ l(x1, 0:1), pdat)
est2 = feols(f(y) ~ l(x1, -1:1), pdat)
# You can use sub selections of the panel data
est_sub = feols(y ~ l(x1, 0:1), pdat[!pdat$period %in% c(2, 4)])
etable(est1, est2, est_sub, order = "f", drop = "Int")
```



```{r}
library(data.table)
pdat_dt = panel(as.data.table(base_did), ~id+period)
# we create a lagged value of the variable x1
pdat_dt[, x1_l1 := l(x1)]
#> [1] TRUE
# Now 
pdat_dt[, c("x1_l1_fill0", "y_f2") := .(l(x1, fill = 0), f(y, 2))]
#> [1] TRUE
head(pdat_dt)
```



```{r A.5.2.3 Creating lag/lead variables}
base_lag = base_did
# we create a lagged value of the variable x1
base_lag$x1.l1 = lag(x1 ~ id + period, 1, base_lag)
head(base_lag)
```


```{r}
library(data.table)
base_lag_dt = as.data.table(base_did)
# we create a lagged value of the variable x1
base_lag_dt[, x1.l1 := lag(x1 ~ id + period, 1)]
```

```{r 5.3 Non-linear in parameters example}
# Generating data:
n = 1000
# x and y: two positive random variables
x = rnorm(n, 1, 5)**2
y = rnorm(n, -1, 5)**2
# E(z) = 2*x + 3*y and some noise
z = rpois(n, 2*x + 3*y) + rpois(n, 1)
base = data.frame(x, y, z)
```

```{r}
result_NL = feNmlm(z~0, base, NL.fml = ~ log(a*x + b*y), NL.start = list(a=1, b=1), lower = list(a=0, b=0))
```

```{r}
print(result_NL)
```


```{r A.5.3.1 Adding fixed-effects to non-linear in parameters models}
# the class of each observation
id = sample(20, n, replace = TRUE)
base$id = id
# the vector of fixed-effects
gamma = rnorm(20)**2
# the new vector z_bis
z_bis = rpois(n, gamma[id] * (2*x + 3*y)) + rpois(n, 1)
base$z_bis = z_bis
```

```{r}
# we add the fixed-effect in the formula
result_NL_fe = feNmlm(z_bis~0|id, base, NL.fml = ~ log(2*x + b*y), NL.start = list(b=1), lower = list(b=0))
# The coef should be around 3
coef(result_NL_fe)
#>        b 
#> 3.024891
# the gamma and the exponential of the fixed-effects should be similar
rbind(gamma, exp(fixef(result_NL_fe)$id[as.character(1:20)]))
```


```{r 5.4 Multi-threading}
# Sample of results:
# 1 nthreads: 3.13s
system.time(fenegbin(Euros ~ log(dist_km)|Origin+Destination+Product+Year, trade, nthreads = 1))
# 2 nthreads: 1.82s
system.time(fenegbin(Euros ~ log(dist_km)|Origin+Destination+Product+Year, trade, nthreads = 2))
# 4 nthreads: 1.17s
system.time(fenegbin(Euros ~ log(dist_km)|Origin+Destination+Product+Year, trade, nthreads = 4))
```

